<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WebApp.Domain\WebApp.Domain.csproj" />
    <ProjectReference Include="..\WebApp.Persistence\WebApp.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Humanizer.Core.es" Version="3.0.10" />
    <PackageReference Include="MediatR" Version="12.1.1" />
  </ItemGroup>
  
  <ItemGroup>
  <InternalsVisibleTo Include="WebApp.Application.Tests" />
  </ItemGroup>
  
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
