// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Persistence;

#nullable disable

namespace WebApp.Persistence.Migrations
{
    [DbContext(typeof(WebAppDbContext))]
    partial class WebAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comisionista",
                            NormalizedName = "COMISIONISTA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Consultor",
                            NormalizedName = "CONSULTOR"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gestor",
                            NormalizedName = "GESTOR"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Aprobador_Gasolina",
                            NormalizedName = "APROBADOR_GASOLINA"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Usuario",
                            NormalizedName = "USUARIO"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "Permiso",
                            ClaimValue = "CrearComision",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "Permiso",
                            ClaimValue = "AprobarComision",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "Permiso",
                            ClaimValue = "ConsultarComision",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "Permiso",
                            ClaimValue = "EliminarComision",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "Permiso",
                            ClaimValue = "ModificarComision",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "Permiso",
                            ClaimValue = "CrearComision_Destinos",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "Permiso",
                            ClaimValue = "ModificarComision_Destinos",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "Permiso",
                            ClaimValue = "EliminarComision_Destinos",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "Permiso",
                            ClaimValue = "CrearGasolina",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "Permiso",
                            ClaimValue = "EliminarGasolina",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "Permiso",
                            ClaimValue = "ModificarGasolina",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "Permiso",
                            ClaimValue = "CrearPrecioGasolina",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "Permiso",
                            ClaimValue = "CrearViatico",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "Permiso",
                            ClaimValue = "EliminarViatico",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "Permiso",
                            ClaimValue = "ConsultarViatico",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebApp.Domain.Accesorio", b =>
                {
                    b.Property<int>("AccesorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AccesorioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Creado_Por")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Fecha_Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Modificado_Por")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("AccesorioId");

                    b.ToTable("accesorios", (string)null);
                });

            modelBuilder.Entity("WebApp.Domain.Comision", b =>
                {
                    b.Property<int>("ComisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ComisionId"));

                    b.Property<int?>("Creado_Por")
                        .HasColumnType("int");

                    b.Property<string>("Departamento")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Fecha_Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Fecha_Regreso")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Fecha_Salida")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Galon_Estimado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Modificado_Por")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Galon_Usado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Presupuesto_Combustible_Aprobado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Presupuesto_Combustible_Estimado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId_Aprobador_Combustible")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("ComisionId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("comisiones", (string)null);
                });

            modelBuilder.Entity("WebApp.Domain.ComisionDestino", b =>
                {
                    b.Property<int>("ComisionDestinoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ComisionDestinoId"));

                    b.Property<int>("ComisionId")
                        .HasColumnType("int");

                    b.Property<int?>("Creado_Por")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Fecha_Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Galones")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Kilometros")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Modificado_Por")
                        .HasColumnType("int");

                    b.HasKey("ComisionDestinoId");

                    b.HasIndex("ComisionId");

                    b.ToTable("comisionDestinos", (string)null);
                });

            modelBuilder.Entity("WebApp.Domain.ComisionUsuario", b =>
                {
                    b.Property<int>("ComisionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("Creado_Por")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<bool>("Es_Piloto")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Fecha_Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Modificado_Por")
                        .HasColumnType("int");

                    b.Property<string>("Nombramiento")
                        .HasColumnType("longtext");

                    b.HasKey("ComisionId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("comisionUsuarios", (string)null);
                });

            modelBuilder.Entity("WebApp.Domain.ComisionViaticos", b =>
                {
                    b.Property<int>("ComisionViaticosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ComisionViaticosId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ComisionId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto_Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Monto_Unitario_Usado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("ViaticoId")
                        .HasColumnType("int");

                    b.HasKey("ComisionViaticosId");

                    b.HasIndex("ViaticoId");

                    b.HasIndex("ComisionId", "UsuarioId");

                    b.ToTable("comisionViaticos", (string)null);
                });

            modelBuilder.Entity("WebApp.Domain.Gasolina", b =>
                {
                    b.Property<int>("GasolinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GasolinaId"));

                    b.Property<int?>("Creado_Por")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha_Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Modificado_Por")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("GasolinaId");

                    b.ToTable("gasolinas", (string)null);
                });

            modelBuilder.Entity("WebApp.Domain.GasolinaPrecio", b =>
                {
                    b.Property<int>("GasolinaPrecioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GasolinaPrecioId"));

                    b.Property<int?>("Creado_Por")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GasolinaId")
                        .HasColumnType("int");

                    b.Property<int?>("Modificado_Por")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GasolinaPrecioId");

                    b.HasIndex("GasolinaId");

                    b.ToTable("gasolinaPrecios", (string)null);
                });

            modelBuilder.Entity("WebApp.Domain.Parte", b =>
                {
                    b.Property<int>("ParteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ParteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Creado_Por")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Fecha_Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Modificado_Por")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("ParteId");

                    b.ToTable("partes", (string)null);
                });

            modelBuilder.Entity("WebApp.Domain.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VehiculoId"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Cilindraje")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<int>("ConsumoKmPorGalon")
                        .HasColumnType("int");

                    b.Property<int?>("Creado_Por")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Fecha_Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GasolinaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<double>("Kilometraje")
                        .HasColumnType("double");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .HasColumnType("longtext");

                    b.Property<int?>("Modificado_Por")
                        .HasColumnType("int");

                    b.Property<string>("Placa")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo_Vehiculo")
                        .HasColumnType("longtext");

                    b.HasKey("VehiculoId");

                    b.HasIndex("GasolinaId");

                    b.ToTable("vehiculos", (string)null);
                });

            modelBuilder.Entity("WebApp.Domain.VehiculoAccesorio", b =>
                {
                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.Property<int>("AccesorioId")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext");

                    b.HasKey("VehiculoId", "AccesorioId");

                    b.HasIndex("AccesorioId");

                    b.ToTable("vehiculoAccesorios", (string)null);
                });

            modelBuilder.Entity("WebApp.Domain.VehiculoParte", b =>
                {
                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.Property<int>("ParteId")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext");

                    b.HasKey("VehiculoId", "ParteId");

                    b.HasIndex("ParteId");

                    b.ToTable("vehiculoPartes", (string)null);
                });

            modelBuilder.Entity("WebApp.Domain.Viatico", b =>
                {
                    b.Property<int>("ViaticoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ViaticoId"));

                    b.Property<int?>("Creado_Por")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha_Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Modificado_Por")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Vigente")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ViaticoId");

                    b.ToTable("viaticos", (string)null);
                });

            modelBuilder.Entity("WebApp.Persistence.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NIT")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre_Completo")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Numero_Contrato")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Puesto")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo_Servicios")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Unidad")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("WebApp.Persistence.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("WebApp.Persistence.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Persistence.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("WebApp.Persistence.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Domain.Comision", b =>
                {
                    b.HasOne("WebApp.Persistence.Models.AppUser", null)
                        .WithMany("Comisiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Domain.Vehiculo", "Vehiculo")
                        .WithMany("Comisiones")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("WebApp.Domain.ComisionDestino", b =>
                {
                    b.HasOne("WebApp.Domain.Comision", "Comision")
                        .WithMany("ComisionDestinos")
                        .HasForeignKey("ComisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comision");
                });

            modelBuilder.Entity("WebApp.Domain.ComisionUsuario", b =>
                {
                    b.HasOne("WebApp.Domain.Comision", "Comision")
                        .WithMany("ComisionUsuarios")
                        .HasForeignKey("ComisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Persistence.Models.AppUser", null)
                        .WithMany("ComisionUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comision");
                });

            modelBuilder.Entity("WebApp.Domain.ComisionViaticos", b =>
                {
                    b.HasOne("WebApp.Domain.Viatico", "Viatico")
                        .WithMany("ComisionViaticos")
                        .HasForeignKey("ViaticoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Domain.ComisionUsuario", "ComisionUsuario")
                        .WithMany("ComisionViaticosList")
                        .HasForeignKey("ComisionId", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComisionUsuario");

                    b.Navigation("Viatico");
                });

            modelBuilder.Entity("WebApp.Domain.GasolinaPrecio", b =>
                {
                    b.HasOne("WebApp.Domain.Gasolina", "Gasolina")
                        .WithMany("GasolinaPrecios")
                        .HasForeignKey("GasolinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gasolina");
                });

            modelBuilder.Entity("WebApp.Domain.Vehiculo", b =>
                {
                    b.HasOne("WebApp.Domain.Gasolina", "Gasolina")
                        .WithMany("Vehiculos")
                        .HasForeignKey("GasolinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gasolina");
                });

            modelBuilder.Entity("WebApp.Domain.VehiculoAccesorio", b =>
                {
                    b.HasOne("WebApp.Domain.Accesorio", "Accesorio")
                        .WithMany("VehiculoAccesorios")
                        .HasForeignKey("AccesorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Domain.Vehiculo", "Vehiculo")
                        .WithMany("VehiculoAccesorios")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accesorio");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("WebApp.Domain.VehiculoParte", b =>
                {
                    b.HasOne("WebApp.Domain.Parte", "Parte")
                        .WithMany("VehiculoPartes")
                        .HasForeignKey("ParteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Domain.Vehiculo", "Vehiculo")
                        .WithMany("VehiculoPartes")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parte");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("WebApp.Domain.Accesorio", b =>
                {
                    b.Navigation("VehiculoAccesorios");
                });

            modelBuilder.Entity("WebApp.Domain.Comision", b =>
                {
                    b.Navigation("ComisionDestinos");

                    b.Navigation("ComisionUsuarios");
                });

            modelBuilder.Entity("WebApp.Domain.ComisionUsuario", b =>
                {
                    b.Navigation("ComisionViaticosList");
                });

            modelBuilder.Entity("WebApp.Domain.Gasolina", b =>
                {
                    b.Navigation("GasolinaPrecios");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("WebApp.Domain.Parte", b =>
                {
                    b.Navigation("VehiculoPartes");
                });

            modelBuilder.Entity("WebApp.Domain.Vehiculo", b =>
                {
                    b.Navigation("Comisiones");

                    b.Navigation("VehiculoAccesorios");

                    b.Navigation("VehiculoPartes");
                });

            modelBuilder.Entity("WebApp.Domain.Viatico", b =>
                {
                    b.Navigation("ComisionViaticos");
                });

            modelBuilder.Entity("WebApp.Persistence.Models.AppUser", b =>
                {
                    b.Navigation("ComisionUsuarios");

                    b.Navigation("Comisiones");
                });
#pragma warning restore 612, 618
        }
    }
}
